// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer Vite env, but allow runtime globals (useful on some hosting providers)
const _viteUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const _viteKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const _globalUrl = (globalThis as any).__SUPABASE_URL || (globalThis as any).supabaseUrl || (globalThis as any).SUPABASE_URL;
const _globalKey = (globalThis as any).__SUPABASE_KEY || (globalThis as any).supabaseKey || (globalThis as any).SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = _viteUrl || _globalUrl;
const SUPABASE_PUBLISHABLE_KEY = _viteKey || _globalKey;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [] as string[];
  if (!SUPABASE_URL) missing.push('VITE_SUPABASE_URL or runtime __SUPABASE_URL');
  if (!SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY or runtime __SUPABASE_KEY');
  const msg = `Missing required Supabase configuration: ${missing.join(', ')}.\n` +
    `Set these in your local .env (Vite) or expose them as runtime globals (e.g. window.__SUPABASE_URL) in your hosting environment.\n` +
    `See README.md -> Environment Configuration for details.`;
  // eslint-disable-next-line no-console
  console.error(msg);
  throw new Error(msg);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});