// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Helper to get stored config from localStorage
function getStoredConfig() {
  try {
    if (typeof window !== 'undefined' && window.localStorage) {
      const stored = localStorage.getItem('sah_supabase_config');
      return stored ? JSON.parse(stored) : null;
    }
  } catch {
    // ignore localStorage errors
  }
  return null;
}

// Prefer stored config (user setup), then Vite env, then runtime globals
const _viteUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const _viteKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const _globalUrl = (globalThis as any).__SUPABASE_URL || (globalThis as any).supabaseUrl || (globalThis as any).SUPABASE_URL;
const _globalKey = (globalThis as any).__SUPABASE_KEY || (globalThis as any).supabaseKey || (globalThis as any).SUPABASE_PUBLISHABLE_KEY;

const _storedConfig = getStoredConfig();
const SUPABASE_URL = _storedConfig?.url || _viteUrl || _globalUrl;
const SUPABASE_PUBLISHABLE_KEY = _storedConfig?.key || _viteKey || _globalKey;

export function isSupabaseConfigured(): boolean {
  return !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});